version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  backend:
    image: agusgiorlando/multifiresim-backend:latest
    ports:
      - "5000:80"
    volumes:
      - ../backend/src/:/app
      - multifiresim_images:/app/images
    depends_on:
        - mongodb
  frontend:
    image: agusgiorlando/multifiresim-frontend:latest
    ports:
      - "8000:5000"
    volumes:
      - ../frontend/src/:/app
      - multifiresim_images:/app/images
    depends_on:
        - backend
  firesim:
    image: agusgiorlando/multifiresim-firesim:latest
    ports:
      - "3000:80"
volumes:
  mongodb_data:  
  multifiresim_images: