apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: firesim-service
spec:
  selector:
    app: firesim
  ports:
    - protocol: TCP
      port: 80
