name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: cd frontend
        run: cd frontend/
      - name: ls -la
        run: ls -la
      - name: Build the Docker image
        working-directory: frontend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multifiresim-frontend:actions-${{github.sha}} -f Dockerfile .
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multifiresim-frontend:actions-${{github.sha}}