name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:  
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        working-directory: frontend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multifiresim-frontend:actions-${{github.sha}} -f Dockerfile .
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multifiresim-frontend:actions-${{github.sha}}

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        working-directory: backend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multifiresim-backend:actions-${{github.sha}} -f Dockerfile .
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multifiresim-backend:actions-${{github.sha}}

  firesim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        working-directory: firesim
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multifiresim-firesim:actions-${{github.sha}} -f Dockerfile .
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/multifiresim-firesim:actions-${{github.sha}}